samsung: extmod: Removed redundant core as it will cause duplicate symbol error.
ONE OF THE ERRORS:
ld.lld: error: duplicate symbol: regmap_check_range_table
>>> defined in drivers/base/regmap/built-in.a(regmap.o)
>>> defined in drivers/built-in.a(base/regmap/regmap.o)

Signed-off-by: Carlo Dee <carlodee.official@gmail.com>